version: "3"

services:
  gluetun:
    build:
      dockerfile: ./Dockerfile.gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER? "Please set the VPN_SERVICE_PROVIDER environment variable"}
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY? "Please set the WIREGUARD_PRIVATE_KEY environment variable"}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY? "Please set the WIREGUARD_PRESHARED_KEY environment variable"}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES? "Please set the WIREGUARD_ADDRESSES environment variable"}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS? "Please set the FIREWALL_OUTBOUND_SUBNETS environment variable"}
    volumes:
      - /lib/modules:/lib/modules:ro
      - gluetun-data:/gluetun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      vpn:
        ipv4_address: 172.32.0.4
        ipv6_address: "fd01:beee:beee::4"
    restart: unless-stopped

  wg-easy:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    networks:
      vpn:
        ipv4_address: 172.32.0.8
        ipv6_address: "fd01:beee:beee::8"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - INIT_PORT=${INIT_PORT}
      - INIT_IPV4_CIDR=${INIT_IPV4_CIDR}
      - INIT_IPV6_CIDR=${INIT_IPV6_CIDR}
    volumes:
      - /lib/modules:/lib/modules:ro
      - wg-easy-data:/etc/wireguard
    restart: unless-stopped

volumes:
  gluetun-data:
  wg-easy-data:

networks:
  vpn:
    name: vpn
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
        - subnet: fd01:beee:beee::/48
          gateway: fd01:beee:beee::1