version: "3"

services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    networks:
      vpn:
        ipv4_address: 172.31.0.8 # Fixed IPv4 address
        ipv6_address: "fd01:beee:beee::8" # Fixed IPv6 address
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    env_file:
      - .env
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./data/wg-easy:/etc/wireguard # Persist WireGuard configuration
    restart: unless-stopped

  gluetun:
    build:
      dockerfile: ./Dockerfile.gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./data/gluetun:/gluetun # Persist gluetun configuration
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      vpn:
        ipv4_address: 172.31.0.4 # Fixed IPv4 address
        ipv6_address: "fd01:beee:beee::4" # Fixed IPv6 address
    restart: unless-stopped

  # AdGuard Home service as DNS server
  # If you do not want to use Adguard Home, you can comment out or remove this service.
  adguardhome:
    image: adguard/adguardhome
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_started
        restart: true
    volumes:
      - ./data/adguardhome/work:/opt/adguardhome/work
      - ./data/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped

networks:
  vpn: # separate bridge network with IPv4 and IPv6
    name: vpn
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.31.0.0/16 # IPv4 subnet
          gateway: 172.31.0.1 # IPv4 gateway
        - subnet: fd01:beee:beee::/48 # IPv6 subnet
          gateway: fd01:beee:beee::1 # IPv6 gateway